MVCTrainMain/MVCTrainProject/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCTrainProject.Models;
using System.Web.Security;

namespace MVCTrainProject.Controllers
{
    public class SecurityController : Controller
    {
        // GET: Security

        car_parkEntities db = new car_parkEntities();
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(employee e)
        {
            var info = db.employee.FirstOrDefault(x => x.email == e.email && x.pword == e.pword || e.email == "admin" && e.pword == "admin");
            if (info != null)
            {
                FormsAuthentication.SetAuthCookie(info.email, false);
                return RedirectToAction("Index", "Park");
            }
            else
            {
                ViewBag.Message = "Şifre veya E-posta Hatalı...";
                return View();
            }
        }
    }
}

MVCTrainMain/MVCTrainProject/Views/Security/Login.cshtml
@model MVCTrainProject.Models.employee
@{ ViewBag.Title = "Login";
                Layout = "~/Views/Shared/_CustomerLayout.cshtml"; }


<h2 style="color:white">Login / Giriş Yap</h2>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <title>Index</title>

</head>
<body>
    @using (Html.BeginForm("Login", "Security", FormMethod.Post))
    {

<br />
                <label style="color:white">E-Mail</label>
                                <br />
                                                <input type="text" name="email" id="email">
                                                                <br />
                                                                                <label style="color:white">Şifre / Password</label>
                                                                                                <br />
                                                                                                                <input type="password" name="pword" id="pword">
                                                                                                                                <br />
                                                                                                                                                <button id="uyari" class="btn btn-success" type="submit">Giriş</button>
                                                                                                                                                                <label style="color: red; font-weight:bold">@ViewBag.Message</label>}
</body>
</html>